export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
//addition
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL';

export const GET_DRAFTS = 'GET_DRAFTS';
export const GET_USER_DRAFTS = 'GET_USER_DRAFTS';
export const DRAFT_ERROR = 'DRAFT_ERROR';
export const DELETE_DRAFT = 'DELETE_DRAFT';
export const ADD_DRAFT = 'ADD_DRAFT';
export const GET_DRAFT = 'GET_DRAFT';

export const GET_ROOM = 'GET_ROOM';
export const GET_ROOMS = 'GET_ROOMS';
export const ROOM_ERROR = 'ROOM_ERROR';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const CLEAR_ROOM = 'CLEAR_ROOM';

export const GET_ROOM_POSTS = 'GET_ROOM_POSTS';

export const GET_EVENT = 'GET_EVENT';
export const BUY_EVENT = 'BUY_EVENT';
export const GET_EVENTS = 'GET_EVENTS';
export const EVENT_ERROR = 'EVENT_ERROR';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const CLEAR_EVENT = 'CLEAR_EVENT';

export const GET_EVENT_POSTS = 'GET_ROOM_POSTS';

export const GET_FRIEND_REQUESTS = 'GET_FRIEND_REQUESTS';
export const GET_FRIEND_REQUESTS_SUCCESS = 'GET_FRIEND_REQUESTS_SUCCESS';
export const GET_FRIEND_REQUESTS_FAIL = 'GET_FRIEND_REQUESTS_FAIL';

export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
export const ACCEPT_FRIEND_REQUEST_FAIL = 'ACCEPT_FRIEND_REQUEST_FAIL';

export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export const REJECT_FRIEND_REQUEST_SUCCESS = 'REJECT_FRIEND_REQUEST_SUCCESS';
export const REJECT_FRIEND_REQUEST_FAIL = 'REJECT_FRIEND_REQUEST_FAIL';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const GET_VENUE = 'GET_VENUE';
export const GET_VENUE_SUCCESS = 'GET_VENUE_SUCCESS';
export const GET_VENUE_FAILED = 'GET_VENUE_FAILED';
export const POST_PAYMENT = 'POST_PAYMENT';
export const POST_PAYMENT_SUCCESS = 'POST_PAYMEN_SUCCESS';
export const POST_PAYMENT_FAILED = 'POST_PAYMENY_FAILED';
